import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {getDatabase,closeDatabaseForTests} from '../database/client';
import {createMember,setMemberPermission} from '../services/member.service';
import {normalizeReportObservations} from '../services/indicator-normalization.service';
import {getReportDetail,listTrendSeries,listReports,buildMemberExportManifest,updateReportPages,deleteReportPage} from '../services/records.service';
import {createUpload} from '../services/upload.service';
import {listPendingExaminationReports,getReportExaminations,previewReportExaminations,saveReportExamination,snapshotExaminationAssignments,restoreExaminationAssignments} from '../services/report-examination.service';
import {parseExaminationTime,resolveExaminationTime} from '../domain/examination';
import type {RequestUser} from '../domain/request-user';

test('examination times preserve precision and reject invented or impossible dates',()=>{
 assert.deepEqual(parseExaminationTime('2024年2月29日'),{value:'2024-02-29',precision:'date'});
 assert.deepEqual(parseExaminationTime('2026/9/1 8:03'),{value:'2026-09-01 08:03',precision:'minute'});
 assert.deepEqual(parseExaminationTime('2026-09-01T08:03:02'),{value:'2026-09-01 08:03:02',precision:'second'});
 for(const value of ['9月1日','入院前','2026-02-29','2026-13-01','2026-09-01 24:00','2026-09-01 08:60']) assert.equal(parseExaminationTime(value),null);
 const lab=resolveExaminationTime({examinationType:'检验',sampledAt:'2026-09-01',issuedAt:'2026-09-02'});
 assert.equal(lab.occurredAt,'2026-09-01');assert.equal(lab.timeKind,'sampled');assert.equal(lab.timePrecision,'date');
 assert.equal(resolveExaminationTime({examinationType:'影像',examinedAt:'2026-09-01 08:30',sampledAt:'2026-09-01'}).occurredAt,'2026-09-01 08:30');
 assert.equal(resolveExaminationTime({timeText:'出院后'}).occurredAt,null);
 assert.equal(resolveExaminationTime({sampledAt:'2026-09-03',issuedAt:'2026-09-02'}).occurredAt,null);
 assert.equal(resolveExaminationTime({sampledAt:'2026-09-02 08:00',issuedAt:'2026-09-02'}).risks.length,0);
});

test('member export includes examination evidence beyond the first report page without leaking another member',()=>{
 const env={...process.env},dir=mkdtempSync(join(tmpdir(),'examination-export-'));process.env.STORAGE_DIR=dir;
 try {
  const db=getDatabase();
  db.exec("INSERT INTO users(id,display_name) VALUES('owner','synthetic')");
  const owner:RequestUser={id:'owner',displayName:'synthetic',provider:'development',authenticated:true,isGatewayAdmin:false};
  const member=createMember(owner,{displayName:'合成成员',relationship:'other'});
  const other=createMember(owner,{displayName:'另一合成成员',relationship:'other'});
  for(let i=0;i<52;i++) {
   const id=`export-${String(i).padStart(2,'0')}`;
   db.prepare("INSERT INTO reports(id,member_id,created_by,report_type,title,status,report_issued_at) VALUES(?,?,'owner','laboratory','synthetic',?,'2026-09-01')").run(id,i===51?other.id:member.id,i===50?'trashed':'ready');
   db.prepare("INSERT INTO report_examinations(id,report_id,source_key,time_text,evidence_json) VALUES(?,?,'synthetic','日期待确认',?)").run(id,id,JSON.stringify([{pageNumber:1,quote:'合成时间证据'}]));
  }
  // One additional active report crosses the 50-report cursor boundary.
  db.exec("UPDATE reports SET status='ready' WHERE id='export-50'");
  const exported=buildMemberExportManifest(owner,member.id);
  assert.equal(exported.reports.length,51);
  assert.equal(new Set(exported.reports.map(r=>r.id)).size,51);
  assert.ok(exported.reports.every(r=>r.id!=='export-51' && r.examinationData.examinations.length===1));
  assert.deepEqual(exported.reports.find(r=>r.id==='export-00')!.examinationData.examinations[0].evidence,[{pageNumber:1,quote:'合成时间证据'}]);
  db.exec("UPDATE reports SET status='trashed' WHERE id='export-00'");
  assert.equal(buildMemberExportManifest(owner,member.id).reports.length,50);
  for(let i=0;i<205;i++)db.prepare("INSERT INTO observations(id,report_id,item_name,result_text) VALUES(?,'export-01','合成指标','80')").run(`detail-${i}`);
  db.exec("UPDATE report_examinations SET occurred_at='2026-09-02',time_kind='sampled',confirmation_status='confirmed' WHERE id='export-01'; INSERT INTO observation_examinations(observation_id,examination_id,assignment_source) VALUES('detail-0','export-01','manual')");
  const detail=getReportDetail(owner,'export-01');
  assert.equal(detail.observations.length,205,'all indicators are returned beyond the previous 200 row limit');
  assert.equal(detail.observations.find(o=>o.id==='detail-0')?.examinationTime,'2026-09-02');

 } finally {closeDatabaseForTests();process.env=env;rmSync(dir,{recursive:true,force:true});}
});

test('examination editing preserves legacy data and atomically enforces ownership and versions',()=>{
 const env={...process.env};const dir=mkdtempSync(join(tmpdir(),'examination-test-'));process.env.STORAGE_DIR=dir;
 try {
  const db=getDatabase();db.exec("INSERT INTO users(id,display_name,is_gateway_admin) VALUES('owner','synthetic',0),('viewer','synthetic',0),('admin','synthetic',1)");
  const owner:RequestUser={id:'owner',displayName:'synthetic',provider:'development',authenticated:true,isGatewayAdmin:false};
  db.exec("INSERT INTO user_identities(id,user_id,provider,subject) VALUES('identity-owner','owner','development','owner'),('identity-viewer','viewer','development','viewer')");
  const member=createMember(owner,{displayName:'合成成员',relationship:'other'});
  setMemberPermission(owner,member.id,{userId:'viewer',permission:'viewer',version:0});
  const report=createUpload(owner,member.id,[{originalName:'synthetic.pdf',data:Buffer.from('%PDF-1.4\n%%EOF')}]);
  const other=createUpload(owner,member.id,[{originalName:'other.pdf',data:Buffer.from('%PDF-1.4\nother\n%%EOF')}]);
  for(const [id,rid,value] of [['a',report.reportId,'120'],['b',report.reportId,'80'],['other',other.reportId,'120']]) db.prepare("INSERT INTO observations(id,report_id,item_name,result_text) VALUES(?,?,'合成指标',?)").run(id,rid,value);
  db.prepare("UPDATE reports SET status='ready',report_type='laboratory',report_issued_at='2026-09-20' WHERE id=?").run(report.reportId);
  db.prepare("UPDATE observations SET item_name='肌酸激酶',normalized_name='肌酸激酶',section_name='生化检验',numeric_value=CAST(result_text AS REAL),unit='U/L',reference_low=40,reference_high=200,reference_text='40-200' WHERE report_id=?").run(report.reportId);
  normalizeReportObservations(report.reportId);
  const initial=getReportExaminations(owner,report.reportId);
  assert.equal(initial.examinations.length,0);assert.equal(initial.observations.length,2);assert.equal(initial.observations[0].examinationId,null);
  const noOcr=previewReportExaminations(owner,report.reportId);
  assert.equal(noOcr.hasOcr,false);assert.equal(noOcr.proposals.length,0);
  assert.throws(()=>previewReportExaminations({...owner,id:'viewer'},report.reportId));
  db.prepare("INSERT INTO report_pages(id,report_id,page_number,original_name,storage_path,mime_type,file_size,sha256) VALUES('history-page',?,99,'synthetic.png','synthetic.png','image/png',1,'synthetic')").run(report.reportId);
  db.prepare("INSERT INTO processing_jobs(id,report_id,page_id,job_type,pipeline_version,deduplication_key,status) VALUES('history-ocr',?,'history-page','ocr','test','history-ocr','completed')").run(report.reportId);
  db.prepare("INSERT INTO ocr_results(id,job_id,page_id,engine,model_version,lines_json) VALUES('history-text','history-ocr','history-page','test','test',?)").run(JSON.stringify([{text:'报告编号：SYNTHETIC'},{text:'采样时间：2026-09-01'},{text:'肌酸激酶 120 U/L'}]));
  db.prepare("UPDATE observations SET evidence_json=? WHERE id='a'").run(JSON.stringify([{pageNumber:99,quote:'肌酸激酶 120 U/L'}]));
  const beforePreview=JSON.stringify(getReportExaminations(owner,report.reportId));
  const proposal=previewReportExaminations(owner,report.reportId);
  assert.equal(JSON.stringify(getReportExaminations(owner,report.reportId)),beforePreview,'preview must not write associations or change versions');
  assert.equal(proposal.proposals.find(p=>p.observations.some(o=>o.observationId==='a'))?.occurredAt,'2026-09-01');
  assert.equal(proposal.proposals.find(p=>p.observations.some(o=>o.observationId==='b'))?.certain,false);
  const input={version:initial.version,reportVersion:initial.reportVersion,requestKey:'first',examination:{examinationType:'检验',sampledAt:'2026-09-01',timeText:'采样 2026-09-01'},observationIds:['a']};
  assert.throws(()=>saveReportExamination({...owner,id:'viewer'},report.reportId,input));
  assert.throws(()=>getReportExaminations({...owner,id:'admin',isGatewayAdmin:true},report.reportId));
  const first=saveReportExamination(owner,report.reportId,input);
  assert.equal(previewReportExaminations(owner,report.reportId).protectedCount,1);
  const exported=buildMemberExportManifest(owner,member.id).reports.find(r=>r.id===report.reportId)!;
  assert.deepEqual(exported.examinationData,first);
  assert.equal(first.version,1);assert.equal(first.examinations[0].occurredAt,'2026-09-01');
  assert.equal(first.observations.find(o=>o.observationId==='b')?.examinationId,null);
  assert.throws(()=>saveReportExamination(owner,report.reportId,input),/已修改/);
  const before=JSON.stringify(getReportExaminations(owner,report.reportId));
  assert.throws(()=>saveReportExamination(owner,report.reportId,{...input,version:first.version,reportVersion:first.reportVersion,requestKey:'invalid',observationIds:['b','other']}),/不属于/);
  assert.equal(JSON.stringify(getReportExaminations(owner,report.reportId)),before);
  const second=saveReportExamination(owner,report.reportId,{...input,version:first.version,reportVersion:first.reportVersion,requestKey:'second',observationIds:['b'],examination:{examinationType:'检验',sampledAt:'2026-09-08'}});
  assert.deepEqual(second.examinations.map(e=>e.occurredAt),['2026-09-01','2026-09-08']);
  const filtered=(from:string,to:string)=>listReports(owner,50,{memberId:member.id,dateFrom:from,dateTo:to}).items.filter(r=>r.id===report.reportId);
  assert.equal(filtered('2026-09-01','2026-09-01').length,1);
  assert.equal(filtered('2026-09-08','2026-09-08').length,1);
  assert.equal(filtered('2026-09-02','2026-09-07').length,0,'one examination must satisfy both date bounds');
  assert.equal(filtered('2026-09-20','2026-09-20').length,0,'fully linked report is filtered by examination dates');
  const points=()=>listTrendSeries(owner,member.id).flatMap(series=>series.points).filter(point=>point.reportId===report.reportId);
  assert.deepEqual(points().map(point=>[point.reportIssuedAt,point.numericValue]),[['2026-09-01',120],['2026-09-08',80]]);
  db.prepare("UPDATE observation_examinations SET examination_id=? WHERE observation_id='b'").run(first.examinations[0].id);
  assert.equal(points().length,2,'conflicting results in one examination are both retained');
  assert.ok(points().every(point=>point.examinationConflict),'every conflicting source is explicitly marked');
  const conflictedSeries=listTrendSeries(owner,member.id).find(series=>series.points.some(point=>point.examinationConflict))!;
  assert.equal(conflictedSeries.latestValue,null);assert.equal(conflictedSeries.delta,null);
  assert.equal(conflictedSeries.abnormalContinuityStatus,'conflict');
  assert.equal(conflictedSeries.recoveredFromAbnormal,false);
  assert.equal(conflictedSeries.consecutiveAbnormalCount,0);
  assert.equal(conflictedSeries.totalAbnormalCount,0);
  assert.equal(conflictedSeries.trendConclusionAllowed,false);assert.equal(conflictedSeries.latestChangeConclusionAllowed,false);
  db.prepare("UPDATE observation_examinations SET examination_id=? WHERE observation_id='b'").run(second.examinations[1].id);
  assert.ok(points().every(point=>!point.examinationConflict),'different examinations are not a result conflict');
  db.prepare("UPDATE report_examinations SET occurred_at='2026-09-01' WHERE id=?").run(second.examinations[1].id);
  const sameDay=listTrendSeries(owner,member.id).find(series=>series.points.some(point=>point.reportId===report.reportId))!;
  assert.equal(sameDay.points.length,2);
  assert.ok(sameDay.points.every(point=>point.timeOrderAmbiguous));
  assert.equal(sameDay.latestValue,null);assert.equal(sameDay.delta,null);
  assert.equal(sameDay.latestChangeConclusionAllowed,false);assert.equal(sameDay.trendConclusionAllowed,false);
  assert.equal(sameDay.recoveredFromAbnormal,false);
  db.prepare("UPDATE report_examinations SET occurred_at='2026-09-01 08:00',time_precision='minute' WHERE id=?").run(first.examinations[0].id);
  assert.ok(points().every(point=>point.timeOrderAmbiguous),'a date-only result cannot be ordered against a timed result on that date');
  db.prepare("UPDATE report_examinations SET occurred_at='2026-09-01 09:00',time_precision='minute' WHERE id=?").run(second.examinations[1].id);
  assert.ok(points().every(point=>!point.timeOrderAmbiguous));
  assert.equal(listTrendSeries(owner,member.id).find(series=>series.points.some(point=>point.reportId===report.reportId))!.latestValue,80);
  db.prepare("UPDATE report_examinations SET occurred_at='2026-09-01',time_precision='date' WHERE id=?").run(first.examinations[0].id);
  db.prepare("UPDATE report_examinations SET occurred_at='2026-09-08',time_precision='date' WHERE id=?").run(second.examinations[1].id);
  db.prepare("UPDATE observations SET result_text='120',numeric_value=120 WHERE id='b'").run();normalizeReportObservations(report.reportId);
  assert.equal(points().length,2,'equal values from different examinations both survive');
  db.prepare("UPDATE report_examinations SET specimen='血清',method='方法甲' WHERE id=?").run(first.examinations[0].id);
  db.prepare("UPDATE report_examinations SET specimen='尿液',method='方法乙' WHERE id=?").run(second.examinations[1].id);
  assert.deepEqual(points().map(point=>[point.comparisonSpecimen,point.comparisonMethod]),[['血清','方法甲'],['尿液','方法乙']]);
  const mixedContext=listTrendSeries(owner,member.id).find(series=>series.points.some(point=>point.reportId===report.reportId))!;
  assert.equal(mixedContext.latestChangeConclusionAllowed,false,'different examination contexts cannot produce a recovery conclusion');
  db.prepare("UPDATE report_examinations SET specimen='',method='' WHERE report_id=?").run(report.reportId);

  const pending=saveReportExamination(owner,report.reportId,{version:second.version,reportVersion:second.reportVersion,requestKey:'pending',id:second.examinations[1].id,observationIds:['b'],examination:{timeText:'出院后'}});
  assert.equal(pending.examinations.find(e=>e.id===second.examinations[1].id)?.occurredAt,null);
  const waiting=listPendingExaminationReports(owner,member.id);
  assert.equal(waiting.length,1);assert.equal(waiting[0].reportId,report.reportId);
  assert.equal(waiting[0].observationCount,1);assert.equal(waiting[0].examinationCount,1);
  assert.deepEqual(listPendingExaminationReports({...owner,id:'viewer'},member.id),waiting);
  assert.throws(()=>listPendingExaminationReports({...owner,id:'admin',isGatewayAdmin:true},member.id));
  db.prepare("UPDATE reports SET status='trashed' WHERE id=?").run(report.reportId);
  assert.deepEqual(listPendingExaminationReports(owner,member.id),[]);
  db.prepare("UPDATE reports SET status='ready' WHERE id=?").run(report.reportId);

  assert.equal(points().length,1,'unconfirmed time is not placed at the discharge date');
  const id=String(second.examinations[0].id);
  assert.throws(()=>db.prepare("INSERT INTO observation_examinations(observation_id,examination_id,assignment_source) VALUES('other',?,'manual')").run(id),/mismatch/);
  assert.equal(getReportExaminations({...owner,id:'viewer'},report.reportId).examinations.length,2);
  // Confirming a group's time without moving its indicators leaves automatic links.
  const confirmed=saveReportExamination(owner,report.reportId,{version:pending.version,reportVersion:pending.reportVersion,requestKey:'confirmed-time',id:second.examinations[1].id,observationIds:[],examination:{examinationType:'检验',sampledAt:'2026-09-08'}});
  assert.equal(confirmed.examinations.find(e=>e.id===second.examinations[1].id)?.confirmationStatus,'confirmed');
  db.prepare("UPDATE observation_examinations SET assignment_source='automatic' WHERE observation_id='b'").run();
  const snapshot=snapshotExaminationAssignments(report.reportId);
  const old=db.prepare("SELECT * FROM observations WHERE id='a'").get()!;
  db.exec('BEGIN IMMEDIATE');
  db.prepare('DELETE FROM observations WHERE report_id=?').run(report.reportId);
  const keys=Object.keys(old);
  db.prepare(`INSERT INTO observations(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...keys.map(key=>key==='id'?'replacement-a':old[key]));
  restoreExaminationAssignments(report.reportId,snapshot);db.exec('COMMIT');
  const restored=getReportExaminations(owner,report.reportId);
  assert.equal(restored.observations.length,2,'omitted result in a manually confirmed examination is retained');
  assert.equal(restored.observations.find(o=>o.observationId==='replacement-a')?.examinationId,id);
  assert.equal(restored.observations.find(o=>o.observationId==='b')?.assignmentSource,'automatic');
  assert.equal(restored.examinations.find(e=>e.id===second.examinations[1].id)?.occurredAt,'2026-09-08');
  const timeEvidence=JSON.stringify([{pageId:'history-page',pageNumber:99,quote:'合成日期证据'}]);
  db.prepare('UPDATE report_examinations SET evidence_json=? WHERE report_id=?').run(timeEvidence,report.reportId);
  db.prepare("UPDATE report_examinations SET confirmation_status='automatic' WHERE id=?").run(second.examinations[1].id);
  updateReportPages(owner,report.reportId,{pages:[{id:'history-page',rotation:0},{id:report.pages[0].id,rotation:0}]});
  const reordered=getReportExaminations(owner,report.reportId);
  assert.ok(reordered.examinations.every(e=>e.evidence[0].pageNumber===1 && e.evidence[0].pageId==='history-page'));
  deleteReportPage(owner,report.reportId,'history-page');
  const deleted=getReportExaminations(owner,report.reportId);
  assert.ok(deleted.examinations.every(e=>e.evidence.length===0));
  assert.equal(deleted.examinations.find(e=>e.id===id)?.occurredAt,'2026-09-01','manual confirmation survives removal of its evidence page');
  assert.equal(deleted.examinations.find(e=>e.id===second.examinations[1].id)?.occurredAt,null,'automatic time loses verification when its only evidence page is removed');
  assert.equal(deleted.examinations.find(e=>e.id===second.examinations[1].id)?.confirmationStatus,'pending');
  db.prepare('DELETE FROM reports WHERE id=?').run(report.reportId);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM report_examinations').get()?.n,0);
 } finally {closeDatabaseForTests();process.env=env;rmSync(dir,{recursive:true,force:true});}
});
